In [ ]:
import pandas as pd
import requests
import datetime
import time

In [ ]:
api_request_counter=0

def checkAPI():
  global api_request_counter
  if(api_request_counter==5):
    time.sleep(65)
    api_request_counter=0

In [ ]:
api_key='ZD8CKE4JL0QTFA2C'
symbol='META'

interval='5min'
sliceMonth=['year1month1','year1month2']


stock_df=pd.DataFrame()
for s in sliceMonth:
  url=f'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY_EXTENDED&symbol={symbol}&interval={interval}&slice={s}&apikey={api_key}&datatype=csv'
  
  checkAPI()

  stock_df=stock_df.append(pd.read_csv(url),ignore_index=True)
  api_request_counter+=1

In [ ]:
stock_df=stock_df.iloc[::-1]
stock_df.reset_index(drop=True,inplace=True)
stock_df

                     time    open      high     low     close  volume
0     2022-09-06 04:05:00  161.44  161.4400  161.44  161.4400     711
1     2022-09-06 04:10:00  160.88  160.8800  160.88  160.8800     320
2     2022-09-06 04:15:00  160.87  160.8700  160.87  160.8700     782
3     2022-09-06 04:45:00  161.28  161.7700  161.28  161.5000    1072
4     2022-09-06 04:50:00  161.60  161.6000  161.60  161.6000     250
...                   ...     ...       ...     ...       ...     ...
7728  2022-11-04 19:40:00   90.72   90.7200   90.70   90.7200    3255
7729  2022-11-04 19:45:00   90.72   90.8000   90.65   90.7100    5187
7730  2022-11-04 19:50:00   90.65   90.6901   90.65   90.6901    1433
7731  2022-11-04 19:55:00   90.73   90.7300   90.63   90.6500    2778
7732  2022-11-04 20:00:00   90.65   90.6500   90.64   90.6500    6823

[7733 rows x 6 columns]

In [ ]:
stock_df.to_csv('meta_stock_data.csv')

In [ ]:
stock_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7733 entries, 0 to 7732
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    7733 non-null   object
 1   open    7733 non-null   float64
 2   high    7733 non-null   float64
 3   low     7733 non-null   float64
 4   close   7733 non-null   float64
 5   volume  7733 non-null   int64
dtypes: float64(4), int64(1), object(1)
memory usage: 362.6+ KB

In [ ]:
stock_news_sentiments=pd.DataFrame()
time_from=datetime.datetime.strptime(stock_df['time'].min(), '%Y-%m-%d %H:%M:%S')
time_to=datetime.datetime.strptime(stock_df['time'].max(), '%Y-%m-%d %H:%M:%S')
limit=200

slideDays=1
datetime_from=time_from
datetime_to=datetime_from+ datetime.timedelta(days=slideDays)

print(time_from)
print(time_to)

for i in range(62):

  time_string_from=datetime_from.strftime('%Y%m%dT%H%M')
  time_string_to=datetime_to.strftime('%Y%m%dT%H%M')
  print(time_string_from,time_string_to)


  url=f'https://www.alphavantage.co/query?function=NEWS_SENTIMENT&tickers={symbol}&apikey={api_key}&time_from={time_string_from}&time_to={time_string_to}&limit={limit}&sort=EARLIEST'
  checkAPI()
  r = requests.get(url)
  api_request_counter+=1
  data = r.json()
  sentiment=pd.DataFrame.from_dict(data['feed'])[['time_published','overall_sentiment_score']]

  stock_news_sentiments=stock_news_sentiments.append(sentiment)
  datetime_from=datetime_to
  datetime_to=datetime_to+ datetime.timedelta(days=slideDays)


stock_news_sentiments.reset_index(drop=True,inplace=True)

2022-09-06 04:05:00
2022-11-04 20:00:00
20220906T0405 20220907T0405
20220907T0405 20220908T0405
20220908T0405 20220909T0405
20220909T0405 20220910T0405
20220910T0405 20220911T0405
20220911T0405 20220912T0405
20220912T0405 20220913T0405
20220913T0405 20220914T0405
20220914T0405 20220915T0405
20220915T0405 20220916T0405
20220916T0405 20220917T0405
20220917T0405 20220918T0405
20220918T0405 20220919T0405
20220919T0405 20220920T0405
20220920T0405 20220921T0405
20220921T0405 20220922T0405
20220922T0405 20220923T0405
20220923T0405 20220924T0405
20220924T0405 20220925T0405
20220925T0405 20220926T0405
20220926T0405 20220927T0405
20220927T0405 20220928T0405
20220928T0405 20220929T0405
20220929T0405 20220930T0405
20220930T0405 20221001T0405
20221001T0405 20221002T0405
20221002T0405 20221003T0405
20221003T0405 20221004T0405
20221004T0405 20221005T0405
20221005T0405 20221006T0405
20221006T0405 20221007T0405
20221007T0405 20221008T0405
20221008T0405 20221009T0405
20221009T0405 20221010T0405
20221010T0405 20221011T0405
20221011T0405 20221012T0405
20221012T0405 20221013T0405
20221013T0405 20221014T0405
20221014T0405 20221015T0405
20221015T0405 20221016T0405
20221016T0405 20221017T0405
20221017T0405 20221018T0405
20221018T0405 20221019T0405
20221019T0405 20221020T0405
20221020T0405 20221021T0405
20221021T0405 20221022T0405
20221022T0405 20221023T0405
20221023T0405 20221024T0405
20221024T0405 20221025T0405
20221025T0405 20221026T0405
20221026T0405 20221027T0405
20221027T0405 20221028T0405
20221028T0405 20221029T0405
20221029T0405 20221030T0405
20221030T0405 20221031T0405
20221031T0405 20221101T0405
20221101T0405 20221102T0405
20221102T0405 20221103T0405
20221103T0405 20221104T0405
20221104T0405 20221105T0405
20221105T0405 20221106T0405
20221106T0405 20221107T0405

In [ ]:
print('from ',stock_news_sentiments['time_published'].min())
print('to ',stock_news_sentiments['time_published'].max())

from  20220611T110941
to  20221105T132351

In [ ]:
stock_news_sentiments.to_csv('sentiments.csv')

In [ ]:
stock_news_sentiments.to_csv('sentiment.csv')

In [ ]:
stock_index_symbol='SPY'

In [ ]:
stock_index_df=pd.DataFrame()
for s in sliceMonth:
  url=f'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY_EXTENDED&symbol={stock_index_symbol}&interval={interval}&slice={s}&apikey={api_key}&datatype=csv'
  
  checkAPI()

  stock_index_df=stock_index_df.append(pd.read_csv(url),ignore_index=True)
  api_request_counter+=1

In [ ]:
stock_index_df=stock_index_df.iloc[::-1]
stock_index_df.reset_index(drop=True,inplace=True)
stock_index_df

,time,open,high,low,close,volume
0,2022-09-06 04:05:00,393.201961,393.341383,392.415218,393.082456,5700
1,2022-09-06 04:10:00,392.893239,392.972909,392.644270,392.713981,3809
2,2022-09-06 04:15:00,392.624352,392.624352,392.305672,392.514806,7663
3,2022-09-06 04:20:00,392.375383,392.474971,392.275795,392.474971,3424
4,2022-09-06 04:25:00,392.574558,392.634311,392.375383,392.375383,7496
...,...,...,...,...,...,...
8416,2022-11-04 19:40:00,375.900000,375.900000,375.900000,375.900000,668
8417,2022-11-04 19:45:00,375.860000,375.920000,375.850000,375.920000,496
8418,2022-11-04 19:50:00,375.890000,375.890000,375.890000,375.890000,352
8419,2022-11-04 19:55:00,375.940000,375.980000,375.670000,375.980000,11561
8420,2022-11-04 20:00:00,375.990000,376.000000,375.820000,376.000000,4374

In [ ]:
stock_index_df.to_csv('spy_index.csv')

In [8]:
import numpy as np

In [10]:
def extract_seqX_outcomeY(data, N, offset):
    """
    Split time-series into training sequence X and outcome value Y
    Args:
        data - dataset 
        N - window size, e.g., 50 for 50 days of historical stock prices
        offset - position to start the split
    """
    X, y = [], []
    
    for i in range(offset, len(data)):
        X.append(data[i-N:i])
        y.append(data[i])
    
    return np.array(X), np.array(y)

In [9]:
x=np.array([1,2,3,4,5])

In [11]:
x,y=extract_seqX_outcomeY(x, 2, 0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  from ipykernel import kernelapp as app

In [12]:
x

array([array([], dtype=int64), array([], dtype=int64), array([1, 2]),
       array([2, 3]), array([3, 4])], dtype=object)

In [13]:
y

array([1, 2, 3, 4, 5])